### ISSUE TITLE
Name conflict with other project for the actual PSX (the Japanese DVR)

### ISSUE THREAD

**Issue by HowlingWolfHWC** [brad-lin/FreePSXBoot#11]
![image](https://user-images.githubusercontent.com/58843152/114438281-893f6e00-9b95-11eb-98cf-ca9c7c087289.png)

**Comment by brad-lin** [comment]
I am the one who chose the name, without consulting anybody.

I am very new to the scene, and I have always known the PlayStation as the PSX. I didn't even know about this japanese PSX DVR. It's just a name, get over it. I could have called it BathroomCleanerUltraPro if I had wanted to.

**Comment by HowlingWolfHWC** [comment]
Did you even read the part where in the picture where it says that there was already other project in the works called "FreePSXBoot" and it is for the actual PSX (DVR)?

**Comment by kraptor** [comment]
I'm laughing like an idiot with the BathroomCleanerUltraPro name, hahahaha. 

@brad-lin you have all my support: your project, your name.

@HowlingWolfHWC it's very disrespectful and childish to stalk over discord channels, take screenshots, post elsewhere and not even mentioning @nicolasnoble so he can defend himself... it's so easy on the internet to harass people while being anonymous... if at least you were constructive, but no.

Let's try to be see what people say on the internet...

https://trends.google.com/trends/explore?date=all&geo=US&q=psx%20ps1,psx%20dvr

Yeah, the DVR clearly wins... nope.

**Comment by nicolasnoble** [comment]
> @HowlingWolfHWC it's very disrespectful and childish to stalk over discord channels, take screenshots, post elsewhere and not even mentioning @nicolasnoble so he can defend himself... it's so easy on the internet to harass people while being anonymous... if at least you were constructive, but no.

Just so we're clear, you're totally hitting the nail on the head with this one. The PlayStation community has been commonly plagued with trolls trying to argue this useless debate for decades now, which has become as toxic as "vi vs emacs" or "tabs vs space".

But the real issue here is the stalking up to Discord, and trying to pull the "public forum" and "public shaming" card to pull me into the debate still, while I clearly signaled before I wasn't interested in it in the slightest. This shows alarming levels of abusive behaviors, similar to "why won't you debate me?! you're the one who's being unreasonable here" toxic trolls.

We don't own you a debate, we don't don't want to hear any argument, we don't care. You've clearly demonstrated that you have no care for people's wishes by trying to force a conversation I didn't want to have to begin with. You've all been blocked from all of my github projects as a result, and beyond.
