### ISSUE TITLE
Wrong project name

### ISSUE THREAD

**Issue by balika011** [brad-lin/FreePSXBoot#2]
PSX is the DVR based on PS2
PS1 is PS-X

**Comment by nicolasnoble** [comment]
Oh hush. You've chosen the wrong debate to nitpick on.

**Comment by HowlingWolfHWC** [comment]
I was just going to say the same!
It should be FreePS-XBoot or FreePSBoot or FreePS1Boot...
Else, everyone will think just as me and be confused with PSX (DVR)

**Comment by HowlingWolfHWC** [comment]
![image](https://user-images.githubusercontent.com/58843152/114287626-4a46d680-9a36-11eb-8e46-d593aeea7e36.png)

![image](https://cdn.discordapp.com/attachments/748052841578627114/830578222629781544/PicsArt_04-10-08.01.04.jpg)

**Comment by CelesteBlue-dev** [comment]
I agree with all above.
FreePSBoot is a good name.

**Comment by ramapcsx2** [comment]
The current name is just fine.
I know it's for the PSX. The classic machine from the 90s. All is well :)

**Comment by HowlingWolfHWC** [comment]
> The current name is just fine.
> I know it's for the PSX. The classic machine from the 90s. All is well :)

As a PlayStation enthusiast, I don't see it that way. PSX is not PS-X.

This is a PSX:
![image](https://user-images.githubusercontent.com/58843152/114291404-14651a80-9a55-11eb-9c66-78205d6c3f93.png)

This is a PS-X:
![image](https://user-images.githubusercontent.com/58843152/114291443-74f45780-9a55-11eb-90f2-9656edd22e90.png)

Imagine you name this exploit FreePS4Boot... It makes zero sense as it is not for PS4, but for PS / PS-X / PSOne

**Comment by noiob** [comment]
let me direct you to https://reddit.com/r/psx/comments/6fwekt/this_is_something_every_psx_fan_needs_at_least/

**Comment by TnA-Plastic** [comment]
A sub-reddit defending its name-choice, lol.

**Comment by nicolasnoble** [comment]
Alright, the typical trolls did the expected trolling and had their fun. This one was opened for long enough now, closing it.

**Comment by TnA-Plastic** [comment]
For some reason I can still post.

I had no intention of trolling, but was only/merely pointing out the elephant in the room.

**Comment by DraconicNEO** [comment]
> 
> 
> For some reason I can still post.
> 
> I had no intention of trolling, but was only/merely pointing out the elephant in the room.
> 
> Calling people Trolls just to "defame" or discredit their argument, doesn't make one's own argument any more valid either.
> 
> The name "FreePSBoot" would have avoided that entire discussion in the first place and avoided any speculation.
> 
> Why insisting on "PSX" instead?
> 
> Oh! Btw.: THX @brad-lin for using that name-scheme! The "Free X Boot" Series just became a Multi-Console Exploit-Series! :)

I don't care what it's called as long as it works

**Comment by nicolasnoble** [comment]
I did leave this issue unlocked for the purpose of letting people continue discussing if they wanted to, but instead, they decided to sealion their discussion into Discord and by creating new issues (#11).

For posterity, what really transpired there is that there is a group of people who are secretly working on an exploit for the [DVR machine called the "PSX"](https://en.wikipedia.org/wiki/PSX_(digital_video_recorder)) since February, and they really didn't like the idea that there's now a project similarly named for a different piece of hardware.

Had the authors come off with something along the lines of "Hey, congratulations on your exploit, but unfortunately, we're currently working on a similarly named project for a different piece of hardware, would you consider renaming yours?" instead of using the very typical pedantic and controversy-laden approach of "tHiS prOjEcT nAme Is wRoNg, tHe PsX iS A dIffEreNt piEcE oF HarDwARe, tHis iS A fAct, YoU'rE jUsT ConFusIng PeOpLe", this would've gone down a completely different path.

We even proposed to meet in the middle by adding a line on top of the readme that says "This is about the exploit for the Sony PlayStation 1, if you were looking for the one for the DVR machine, look here instead", but this option is now off the table after their continuous harassment of people, and basically saying that the only acceptable option is to rename this project.

So this is now locked, and any future debate or discussion around this will be met with further locks and bans, as it is blatant sealioning.
