### ISSUE TITLE
I have some doubts can someone please clearified them please?

### ISSUE THREAD

**Issue by diamondhands97** [brad-lin/FreePSXBoot#49]
When I create a Freepsxboot mc, can I use it in any ps1 and psone? (like freemcboot) or I only can use it in that model and bios version?

This works on ntsc-j ps1 and psone consoles?

**Comment by hurda** [comment]
Only with a model using the same BIOS-version, most of the time it's the same model (except 100x). See the list in the README.

Disc-unlock doesn't work on Japanese PS1s except for very early ones, but booting to Unirom does work. From there you can use the disc-swap-method.
What PSones do you mean: Japanese, US or PAL?

**Comment by diamondhands97** [comment]
> 
> 
> Only with a model using the same BIOS-version, most of the time it's the same model (except 100x). See the list in the README.
> 
> Disc-unlock doesn't work on Japanese PS1s except for very early ones, but booting to Unirom does work. From there you can use the disc-swap-method.
> What PSones do you mean: Japanese, US or PAL?

Thanks for you reply, with disc-unlock you mean burned disc's right? 

Psone's from every region

With the except 100x you mean the psone's right?

**Comment by Stab-X** [comment]
see #36

**Comment by hurda** [comment]
´Thanks for you reply, with disc-unlock you mean burned disc's right?´
Yes, and originals from another region.

´Psone's from every region´
On PAL PSone console the same restriction applies as for Japanese PS1-consoles

´With the except 100x you mean the psone's right?´
No, I mean 100x, i.e. the very first models ever released. PSone are the tiny ones released much later, with the model-name SCPH-10x

Please read the README.

**Comment by Ichisuke83** [comment]
> `Thanks for you reply, with disc-unlock you mean burned disc's right?`
> Yes, and originals from another region.
> 
> `Psone's from every region`
> On PAL PSone console the same restriction applies as for Japanese PS1-consoles with regard to only accepting discs from the same region.
> 
> `With the except 100x you mean the psone's right?`
> No, I mean 100x, i.e. the very first models ever released. PSone are the tiny ones released much later, with the model-name SCPH-10x
> 
> Please read the README.

Wait... PAL PSOne can boot imports with Unirom... Since I can do that with freepsxboot.... From what I understood PAL PSOne won't boot games that change video output to NTSC, it's not really a "region block" more a "video change detection block". For example if you have an MM3 chip installed on a PAL PSOne you shouldn't be able to boot import games because the console will detect the video output change from PAL to NTSC and freeze. With the ONEchip this has been bypassed because the console boot directly in NTSC from start(PAL games will run in PAL video output). With Unirom this problem doesn't exist at all. I tested Unirom on 2 PAL PSOne consoles using an original copy of Chrono Cross....

**Comment by TopHatMan** [comment]
I got a scph-7000 can it only boot jp rips or what a bout patches to jp?

**Comment by Ichisuke83** [comment]
> I got a scph-7000 can it only boot jp rips or what a bout patches to jp?

Patching PAL/US games to JP is probably the easiest way

**Comment by hurda** [comment]
`With Unirom this problem doesn't exist at all.`
Maybe the license-check fails gracefully?

**Comment by TopHatMan** [comment]
> > I got a scph-7000 can it only boot jp rips or what a bout patches to jp?
> 
> Patching PAL/US games to JP is probably the easiest way but you'll still need a modchip in the console... The other way is to swap disc using an original Japanese game or Japanese boot disc... Unirom won't work on Japanese models since the "unlock" command simply won't work.

I got two copys I got one game I patched to Jp and one that is JP , It wont work says locked drive or cd wrong.

**Comment by Ichisuke83** [comment]
> `With Unirom this problem doesn't exist at all.`
> Maybe the license-check fails gracefully?

I don't understand what you are implying. As I said on 2 PAL PSOne SCPH-102 UNIROM works just fine...

**Comment by TopHatMan** [comment]
Should I try burn the game slower ?

**Comment by TopHatMan** [comment]
> > I got a scph-7000 can it only boot jp rips or what a bout patches to jp?
> 
> Patching PAL/US games to JP is probably the easiest way but you'll still need a modchip in the console... The other way is to swap disc using an original Japanese game or Japanese boot disc... Unirom won't work on Japanese models since the "unlock" command simply won't work.

rereading this I need a modchip or a JP disc , well I Got a lot JP games. So what would be procedure boot unirom , boot jp g ame then swap?

**Comment by Ichisuke83** [comment]
> > > I got a scph-7000 can it only boot jp rips or what a bout patches to jp?
> > 
> > 
> > Patching PAL/US games to JP is probably the easiest way but you'll still need a modchip in the console... The other way is to swap disc using an original Japanese game or Japanese boot disc... Unirom won't work on Japanese models since the "unlock" command simply won't work.
> 
> rereading this I need a modchip or a JP disc , well I Got a lot JP games. So what would be procedure boot unirom , boot jp g ame then swap?

Exactly. In this case Unirom will act like a normal swap disc. You still have to block the lid sensor. UNIROM will serve only to stop the original disc from spinning, making the swap easier.
Boot UNIROM, open the lid, block the lid sensor, original will start spinning, use the SWAP JP option, original will stop, replace with import/backup, press play. It should work. You can close the lid but the lid sensor must stay locked so find a way to block it down. Keep in mind that doing this can bring issues for games that have multiple audio tracks etc (games with very different TOC informations). On Japanese console a modchip is still probably the best way since the console will read the TOC information from the backup/import that you must have previously "region patched to Japanese" and that will boot from start.
