### ISSUE TITLE
Formatting using memory card annihilator v2 guide, UPDATED

### ISSUE THREAD

**Issue by invaderlex** [brad-lin/FreePSXBoot#51]
I have 100% success formatting FreePSXBoot MC with MCA v2.

I follow this step to format with a ps2 without freezing it. 

1.-insert an USB with MCA V2 in it.
2.-Run and old version of launchELF (uLaunchELF v4.39) from here https://drive.google.com/file/d/14QEU0CW3vI_T1xma1BDGk-mKDbOGKaZK/view?usp=sharing
3.-Insert  FreePSXboot MC in slot1
4.-Insert a normal PS2 MC in slot 2 (Do not skip this step, is necessary)
5.-In uLaunch open MC1:\ (You will see nothing there)
6.-go Back to root
7.-In uLaunch open MC2:\ (You will see its content)
8.-go Back to root
9.-In uLaunch open mass:\
10.-Run MCA from the USB
11.-The two MC will appear as options and the program will work normally.
12.-Format MC1 using MCA.

If you go directly to MCA Skipping the first steps the PS2 will freeze.

UPDATED1: step 4 is necessary, works with an old version of launchELF, I shared mine.
UPDATED2: Thanks to VRtinker for testing and confirming that this does not work with newer version of LaunchELF.
UPDATED3: Work with a few images only not all, tested with 2.0, 2.1, 2,2 and 3.0. Issue closed. Needs more testing. I'm formatting with unirom CD now.

**Comment by VRtinker** [comment]
This doesn't work for me. I don't know if you are using FreeDVDBoot to get to Ulaunch, and if so, if that makes any difference, but for me, I use FreeMCBoot to get to Ulaunch, remove the PS2 MC (it doesn't matter if insert another PS2 MC without or without FreeMCBoot in it in slot 2), but as soon as I insert the FreePSXBoot MC in slot 1 and try to browse it, I get a soft-lock. Same if I load MCA without any MC inserted and then insert the FreePSXBoot one.

Check #39, because that's truly the only way to format without needing "luck" or any other device other than a previously successfully flashed FreeMCBoot MC and a PS1.

If you are using a FreeMCBoot .mcd image from April 14th or before that, then your "method" would work, but every release past that date incorporates changes that invariably lock up a PS2 immediately, in every context, no matter what.

**Comment by invaderlex** [comment]
This is my configuration

FMCB 1.8 test 22, 2008 (indeed a very old one)
LaunchELF v4.39
MCA V2
PS2 MODEL: SCPH-39001

Thanks, then it must be the version of FreeMCBoot.

**Comment by invaderlex** [comment]
> This doesn't work for me. I don't know if you are using FreeDVDBoot to get to Ulaunch, and if so, if that makes any difference, but for me, I use FreeMCBoot to get to Ulaunch, remove the PS2 MC (it doesn't matter if insert another PS2 MC without or without FreeMCBoot in it in slot 2), but as soon as I insert the FreePSXBoot MC in slot 1 and try to browse it, I get a soft-lock. Same if I load MCA without any MC inserted and then insert the FreePSXBoot one.
> 
> Check #39, because that's truly the only way to format without needing "luck" or any other device other than a previously successfully flashed FreeMCBoot MC and a PS1.
> 
> If you are using a FreeMCBoot .mcd image from April 14th or before that, then your "method" would work, but every release past that date incorporates changes that invariably lock up a PS2 immediately, in every context, no matter what.

This is my configuration

FMCB 1.8 test 22, 2008 (indeed a very old one)
LaunchELF v4.39
MCA V2
PS2 MODEL: SCPH-39001

Thanks, then it must be the version of FreeMCBoot.

**Comment by VRtinker** [comment]
> This is my configuration
> 
> FMCB 1.8 test 22, 2008 (indeed a very old one)
> LaunchELF v4.39
> MCA V2
> PS2 MODEL: SCPH-39001
> 
> Thanks, then it must be the version of FreeMCBoot.

I'm pretty positive it has to do with the version of FreePSXBoot you are using (pre-April 14th), because after that, PS2s get locked-up even without any other PS2 MC plugged in (FreeMCBoot doesn't play any role in the lockup, so being on an earlier version wouldn't make a difference). I tested on all my PS2s (3XXXXX, 5XXXXX, 7XXXXX and 77XXXX models), they all lockup as soon as the FreePSXBoot MC is inserted without any FreeMCBoot MC being plugged in at all. FreePSXBoot is da bomb!

Either way, update your software man! :-D

**Comment by invaderlex** [comment]
> > This is my configuration
> > FMCB 1.8 test 22, 2008 (indeed a very old one)
> > LaunchELF v4.39
> > MCA V2
> > PS2 MODEL: SCPH-39001
> > Thanks, then it must be the version of FreeMCBoot.
> 
> I'm pretty positive it has to do with the version of FreePSXBoot you are using (pre-April 14th), because after that, PS2s get locked-up even without any other PS2 MC plugged in (FreeMCBoot doesn't play any role in the lockup, so being on an earlier version wouldn't make a difference). I tested on all my PS2s (3XXXXX, 5XXXXX, 7XXXXX and 77XXXX models), they all lockup as soon as the FreePSXBoot MC is inserted without any FreeMCBoot MC being plugged in at all. FreePSXBoot is da bomb!
> 
> Either way, update your software man! :-D

I used the  FreeMCBoot images from  github.com/brad-lin/FreePSXBoot/, it says "the images are updated. Older versions can be found in the images directory." I used the updated Images. After launching ulaunchELF I can put a Card with FreeMCBoot  and it will not freeze. I also own a PS2 slim, worked there too. Try Using ulaunchELF v4.39. Use mine, (https://drive.google.com/file/d/14QEU0CW3vI_T1xma1BDGk-mKDbOGKaZK/view?usp=sharing)
